steps:
  - id: 'build images'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}', '-t', '${_IMAGE_NAME}:${BUILD_ID}', '.']
  - id: 'push latest image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:latest']
  - id: 'push hash image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:${BUILD_ID}']
  - id: 'deploy cloud run'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud run deploy df-messenger-integration --image ${_IMAGE_NAME} --platform managed --region ${_CLOUD_RUN_REGION} --allow-unauthenticated --labels=commit=${BUILD_ID}

substitutions:
  _IMAGE_NAME: 'gcr.io/${_GCP_PROJECT}/df-messenger-integration'
  _CLOUD_RUN_REGION: 'europe-west1'
  _AGENT_ID: 'c4334d7b-b59f-4373-819a-bae2f4e931db'
  _CHAT_TITLE: 'ticketing agent'
  _BOT_MESSAGE: '#8c1b2e'
  _BUTTON_TITLE_BAR_COLOR: ''
  _CHAT_BG_COLOR: ''
  _FONT_ICON: ''
  _SEND_ICON: ''
  _USER_MESSAGE: ''

options:
  dynamic_substitutions: true
timeout: 900s

